# Generated by Django 5.0.6 on 2024-06-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyfile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/'),
        ),
    ]
